### ISSUE TITLE
plotSparkTable() no longer exists?

### ISSUE THREAD

**Issue by ywugsg** [alexkowa/sparkTable#9]
Hi, I am using this manual for SparkTable package: https://web.warwick.ac.uk/statsdept/user2011/TalkSlides/Contributed/18Aug_0950_FocusVI_4-ReportingData_2-Kowarik.pdf and it tells me there are functions like plotSparkLine, plotSparkTable etc. but they have all disappeared? What are the alternatives??

When I tried to use plot() on a sparktable, it gave me an error 

Error in as.double(y) : 
  cannot coerce type 'S4' to vector of type 'double'

What's happening??????

**Comment by alexkowa** [comment]
Since the presentation in 2011 we have changed the syntax of the package quite a bit. The help files of the package are up to date however. In short: plot is used to show the line on the display and "export" creates the file.
If you provide me with an email adress, I cant send u a current (not-yet published) paper about the package.

**Comment by cksun** [comment]
Hi Alexander,

I would like to ask for a current paper for this package.

Kai

On Fri, Jun 26, 2015 at 4:14 AM, Alexander Kowarik <notifications@github.com

**Comment by alexkowa** [comment]
Just give me your email adress and I will send it to you.
